"""
Stock symbol lists for each market category.
"""

NASDAQ_100 = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "AVGO", "COST", "NFLX",
    "AMD", "ADBE", "PEP", "CSCO", "INTC", "CMCSA", "TMUS", "TXN", "QCOM", "AMGN",
    "INTU", "AMAT", "ISRG", "BKNG", "HON", "VRTX", "LRCX", "REGN", "MU", "ADI",
    "PANW", "KLAC", "MDLZ", "SBUX", "SNPS", "GILD", "CDNS", "MELI", "CTAS", "CRWD",
    "PYPL", "MAR", "ORLY", "CSX", "MNST", "NXPI", "WDAY", "PCAR", "MRVL", "CPRT",
    "ROST", "DXCM", "ADSK", "AEP", "FTNT", "ABNB", "PAYX", "KDP", "LULU", "MCHP",
    "ODFL", "CHTR", "KHC", "IDXX", "GEHC", "AZN", "VRSK", "FAST", "CTSH", "CSGP",
    "EXC", "DDOG", "EA", "BKR", "FANG", "XEL", "BIIB", "ON", "CDW", "TTD",
    "TEAM", "CCEP", "GFS", "MDB", "ZS", "ILMN", "CEG", "DLTR", "WBD",
    "MRNA", "SIRI", "LCID", "RIVN", "DASH", "COIN", "ARM", "SMCI", "PLTR", "MSTR",
    "GOOG", "LIN", "ASML", "PDD", "ROP", "TTWO",
]

SP_500 = [
    "MMM", "AOS", "ABT", "ABBV", "ACN", "ADBE", "AMD", "AES", "AFL", "A",
    "APD", "ABNB", "AKAM", "ALB", "ARE", "ALGN", "ALLE", "LNT", "ALL", "GOOGL",
    "GOOG", "MO", "AMZN", "AMCR", "AEE", "AEP", "AXP", "AIG", "AMT", "AWK",
    "AMP", "AME", "AMGN", "APH", "ADI", "AON", "APA", "APO", "AAPL", "AMAT",
    "APP", "APTV", "ACGL", "ADM", "ARES", "ANET", "AJG", "AIZ", "T", "ATO",
    "ADSK", "ADP", "AZO", "AVB", "AVY", "AXON", "BKR", "BALL", "BAC", "BAX",
    "BDX", "BRK-B", "BBY", "TECH", "BIIB", "BLK", "BX", "BK", "BA",
    "BKNG", "BSX", "BMY", "AVGO", "BR", "BRO", "BF-B", "BLDR", "BG", "BXP",
    "CHRW", "CDNS", "CPT", "CPB", "COF", "CAH", "CCL", "CARR", "CVNA", "CAT",
    "CBOE", "CBRE", "CDW", "COR", "CNC", "CNP", "CF", "CRL", "SCHW", "CHTR",
    "CVX", "CMG", "CB", "CHD", "CIEN", "CI", "CINF", "CTAS", "CSCO", "C",
    "CFG", "CLX", "CME", "CMS", "KO", "CTSH", "COHR", "COIN", "CL", "CMCSA",
    "FIX", "CAG", "COP", "ED", "STZ", "CEG", "COO", "CPRT", "GLW", "CPAY",
    "CTVA", "CSGP", "COST", "CTRA", "CRH", "CRWD", "CCI", "CSX", "CMI", "CVS",
    "DHR", "DRI", "DDOG", "DVA", "DECK", "DE", "DELL", "DAL", "DVN", "DXCM",
    "FANG", "DLR", "DG", "DLTR", "D", "DPZ", "DASH", "DOV", "DOW", "DHI",
    "DTE", "DUK", "DD", "ETN", "EBAY", "SATS", "ECL", "EIX", "EW", "EA",
    "ELV", "EME", "EMR", "ETR", "EOG", "EPAM", "EQT", "EFX", "EQIX", "EQR",
    "ERIE", "ESS", "EL", "EG", "EVRG", "ES", "EXC", "EXE", "EXPE", "EXPD",
    "EXR", "XOM", "FFIV", "FDS", "FICO", "FAST", "FRT", "FDX", "FIS", "FITB",
    "FSLR", "FE", "FISV", "F", "FTNT", "FTV", "FOXA", "FOX", "BEN", "FCX",
    "GRMN", "IT", "GE", "GEHC", "GEV", "GEN", "GNRC", "GD", "GIS", "GM",
    "GPC", "GILD", "GPN", "GL", "GDDY", "GS", "HAL", "HIG", "HAS", "HCA",
    "DOC", "HSIC", "HSY", "HPE", "HLT", "HOLX", "HD", "HON", "HRL", "HST",
    "HWM", "HPQ", "HUBB", "HUM", "HBAN", "HII", "IBM", "IEX", "IDXX", "ITW",
    "INCY", "IR", "PODD", "INTC", "IBKR", "ICE", "IFF", "IP", "INTU", "ISRG",
    "IVZ", "INVH", "IQV", "IRM", "JBHT", "JBL", "JKHY", "J", "JNJ", "JCI",
    "JPM", "KVUE", "KDP", "KEY", "KEYS", "KMB", "KIM", "KMI", "KKR", "KLAC",
    "KHC", "KR", "LHX", "LH", "LRCX", "LVS", "LDOS", "LEN", "LII", "LLY",
    "LIN", "LYV", "LMT", "L", "LOW", "LULU", "LITE", "LYB", "MTB", "MPC",
    "MAR", "MLM", "MAS", "MA", "MKC", "MCD", "MCK", "MDT", "MRK",
    "META", "MET", "MTD", "MGM", "MCHP", "MU", "MSFT", "MAA", "MRNA", "TAP",
    "MDLZ", "MPWR", "MNST", "MCO", "MS", "MOS", "MSI", "MSCI", "NDAQ", "NTAP",
    "NFLX", "NEM", "NWSA", "NWS", "NEE", "NKE", "NI", "NDSN", "NSC", "NTRS",
    "NOC", "NCLH", "NRG", "NUE", "NVDA", "NVR", "NXPI", "ORLY", "OXY", "ODFL",
    "OMC", "ON", "OKE", "ORCL", "OTIS", "PCAR", "PKG", "PLTR", "PANW",
    "PH", "PAYX", "PYPL", "PNR", "PEP", "PFE", "PCG", "PM", "PSX", "PNW",
    "PNC", "POOL", "PPG", "PPL", "PFG", "PG", "PGR", "PLD", "PRU", "PEG",
    "PTC", "PSA", "PHM", "PWR", "QCOM", "DGX", "RL", "RJF", "RTX",
    "O", "REG", "REGN", "RF", "RSG", "RMD", "RVTY", "HOOD", "ROK", "ROL",
    "ROP", "ROST", "RCL", "SPGI", "CRM", "SBAC", "SLB", "STX", "SRE",
    "NOW", "SHW", "SPG", "SWKS", "SJM", "SNA", "SOLV", "SO", "LUV",
    "SWK", "SBUX", "STT", "STLD", "STE", "SYK", "SMCI", "SYF", "SNPS", "SYY",
    "TMUS", "TROW", "TTWO", "TPR", "TRGP", "TGT", "TEL", "TDY", "TER", "TSLA",
    "TXN", "TPL", "TXT", "TMO", "TJX", "TKO", "TTD", "TSCO", "TT", "TDG",
    "TRV", "TRMB", "TFC", "TYL", "TSN", "USB", "UBER", "UDR", "ULTA", "UNP",
    "UAL", "UPS", "URI", "UNH", "UHS", "VLO", "VTR", "VLTO", "VRSN", "VRSK",
    "VZ", "VRTX", "VRT", "VTRS", "VICI", "V", "VST", "VMC", "WRB", "GWW",
    "WAB", "WMT", "DIS", "WBD", "WM", "WAT", "WEC", "WFC", "WELL", "WST",
    "WDC", "WY", "WSM", "WMB", "WTW", "WDAY", "WYNN", "XEL", "XYL", "YUM",
    "ZBRA", "ZBH", "ZTS",
]

SET_THAI_100 = [
    "PTT.BK", "ADVANC.BK", "SCC.BK", "CPALL.BK", "AOT.BK", "GULF.BK", "BDMS.BK",
    "KBANK.BK", "SCB.BK", "BBL.BK", "KTB.BK", "TRUE.BK", "MINT.BK", "BEM.BK",
    "PTTGC.BK", "PTTEP.BK", "IRPC.BK", "TOP.BK", "BCP.BK", "BANPU.BK",
    "IVL.BK", "TU.BK", "CPN.BK", "HMPRO.BK", "BJC.BK", "MAKRO.BK",
    "BGRIM.BK", "GPSC.BK", "EGCO.BK", "RATCH.BK", "EA.BK", "SUPER.BK",
    "BTS.BK", "CRC.BK", "OR.BK", "COM7.BK", "SAWAD.BK", "MTC.BK",
    "KCE.BK", "DELTA.BK", "HANA.BK", "STA.BK", "STGT.BK",
    "AWC.BK", "CK.BK", "WHA.BK", "LH.BK", "AP.BK", "SPALI.BK", "ORI.BK",
    "CENTEL.BK", "ERW.BK", "PLANB.BK", "VGI.BK", "CBG.BK", "OSP.BK",
    "GLOBAL.BK", "JMART.BK", "RS.BK", "TIDLOR.BK", "TTB.BK", "TISCO.BK",
    "KKP.BK", "SCGP.BK", "AMATA.BK", "GFPT.BK", "CPF.BK", "TVO.BK",
    "THANI.BK", "SINGER.BK", "CHG.BK", "BCH.BK", "BH.BK",
    "BEAUTY.BK", "MEGA.BK", "TOA.BK", "DCC.BK", "SAPPE.BK",
    "MAJOR.BK", "WORK.BK", "III.BK", "BROOK.BK", "NER.BK",
    "SIRI.BK", "SC.BK", "NOBLE.BK", "ANAN.BK", "QH.BK",
    "JAS.BK", "DTAC.BK", "INTUCH.BK", "THCOM.BK", "INSET.BK",
    "RBF.BK", "MC.BK", "SYNEX.BK", "SABINA.BK", "BEAUTY.BK",
]

THAI_ENERGY_PALM = [
    # พลังงาน
    "PTT.BK", "PTTEP.BK", "PTTGC.BK", "TOP.BK", "IRPC.BK", "BCP.BK",
    "BANPU.BK", "GULF.BK", "GPSC.BK", "BGRIM.BK", "EGCO.BK", "RATCH.BK",
    "EA.BK", "SUPER.BK", "OR.BK", "BCPG.BK", "GUNKUL.BK", "SPCG.BK",
    "WHAUP.BK", "ACE.BK", "DEMCO.BK", "TPIPP.BK",
    # ปาล์ม / พืชพลังงาน
    "TVO.BK", "UPOIC.BK", "LST.BK", "CPI.BK", "UVAN.BK", "SAUCE.BK",
    "TWPC.BK", "KTIS.BK", "KBS.BK", "RBF.BK",
]

ALL_CATEGORIES = {
    "nasdaq100": {"name": "NASDAQ 100", "symbols": NASDAQ_100},
    "sp500": {"name": "S&P 500", "symbols": SP_500},
    "set100": {"name": "SET Thai 100", "symbols": SET_THAI_100},
    "thai_energy": {"name": "Thai Energy & Palm", "symbols": THAI_ENERGY_PALM},
}
